Made modifications.
NoComment1105/upgrade-everything pull request #4
Opened 2021-12-24 03:10 UTC by mhmatthewhugley

Being able to upgrade a bow into crossbow was added. Uses crafting to upgrade they just add a iron ingot and tripwire hook. This is the exact material difference besides 1 other material, if you were going to make a crossbow first instead of a bow.

Chainmail armor to iron was added. Uses iron ingot in smithing table.

Gold to chainmail armor was modified instead of using cobblestone it uses a minecraft:chain which is craftable and can be found.

Gold to iron armor was removed. (Because it would skip the chainmail stage) (Based on the "Protection value" section and the "Tiers" section of this page "https://minecraft.fandom.com/wiki/Armor")

Wooden to stone tools was modified, now it uses the miencraft:stone instead of cobblestone. (Because that is more fitting with the look of stone tools.)

2021-12-24 03:11 UTC, mhmatthewhugley commented
Also the README.md was modified to include the new features and features that was missing. And adding my name and role and everything to the contributor section. And other changes might have been made. I think I listed everything though.

2021-12-24 07:40 UTC, NoComment1105 requested changes
Just a single request. But otherwise looking good!

2021-12-24 07:40 UTC, NoComment1105 commented on upgrade_everything_v1.5.2/data/upgrade-everything/recipes/wooden-to-stone-hoe.json
> +		"item": "minecraft:stone"
I'd prefer cobblestone to stay used here, due to cobblestone being what is used to craft stone toosl in the first place
```suggestion
                "item": "minecraft:cobblestone"
```

2021-12-24 15:17 UTC, mhmatthewhugley commented
Yes that makes a lot of sense I guess I just forgot about that when I made modifications.

2021-12-24 15:17 UTC, NoComment1105 commented
You need to do the other 4 too lmao

2021-12-24 15:22 UTC, mhmatthewhugley commented
Did I do it all right?

2021-12-24 15:23 UTC, NoComment1105 approved these changes
All good, will merge tonight

2021-12-24 15:24 UTC, mhmatthewhugley commented
I also updated the readme to change it from stone to cobblestone.

2021-12-24 15:34 UTC, NoComment1105 approved these changes

2021-12-24 15:59 UTC, mhmatthewhugley commented
My server would not start up unless it was put in a crafting directory so that is what those changes are for. (Java 17) (Paper MC 402)

2021-12-24 16:17 UTC, NoComment1105 commented
The reason it wasn't starting is due to the recipe file being wrong. The reason it loads now is because that director does nothing

2021-12-24 16:27 UTC, mhmatthewhugley commented
I think I fixed the recipe file.

2021-12-24 16:49 UTC, mhmatthewhugley commented
I was able to fix it but by using crafting instead of the smithing table it would not keep enchantments.

2021-12-24 16:50 UTC, NoComment1105 commented
I'm gonna have to test this before merge because I've not no idea what's actually going on

2021-12-24 16:51 UTC, mhmatthewhugley commented
Sounds good. I expected that. I am putting the bow to crossbow back on the smithing table cause if I did it with the crafting table it would not keep enchantments

2021-12-26 21:04 UTC, mhmatthewhugley commented
How did your christmas go? How did testing it go? Does anything need to be changed?

2021-12-26 21:23 UTC, NoComment1105 commented
Haven't had time

2022-01-12 00:13 UTC, mhmatthewhugley commented
When you test it let me know how it goes and if anything needs to be changed.

2022-04-20 02:58 UTC, mhmatthewhugley commented
> Haven't had time

Whenever you can that would be great so I can archive my repository.

2022-12-29 19:45 UTC, closed without merging